import type { Metadata } from "next";
import { Libre_Franklin, Roboto } from "next/font/google";

import { cn } from "~/lib/utils";

import "./globals.css";

const libre_franklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-libre_franklin",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "NextJS Boilerplate",
  description: "Generated by create next app",
};

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
  }>,
) {

  return (
    <html lang={'en'}>
      <body
        className={cn(
          "flex min-h-screen w-full flex-col antialiased",
          libre_franklin.variable,
          roboto.variable,
        )}
      >
        {props.children}
      </body>
    </html>
  );
}
